---
title: "PA1_template"
author: "Warren Chanzit"
date: "April 3, 2016"
output: 
  html_document: 
    keep_md: yes
---

## Pre-Analysis set-up.
### Import packages and set working directory.
```{r}
library(dplyr)
library(ggplot2)
library(reshape2)
```

### Read and process data.
```{r, echo = TRUE}
data <- read.csv("activity.csv")
data$date <- as.Date(data$date)
data2 <- na.omit(data)
```

## Calculate and plot total steps per day.
```{r, echo = TRUE}
daySteps <- with(data2, tapply(steps, date, sum))
hist(daySteps,
     breaks = 10,
     xlab = "Steps",
     main = "Daily Steps Taken")
```

```{r, echo = TRUE}
mean(daySteps)
median(daySteps)
```

## Investigate average daily activity patterns.
```{r, echo = TRUE}
intervals <- with(data2, tapply(steps, interval, mean))
plot(names(intervals),intervals,type = "l")
intervals[intervals == max(intervals)]
```

## Imput missing values.
```{r, echo = TRUE}
sum(is.na(data))
```

```{r, echo = TRUE}
int_df <- as.data.frame(intervals)
names(int_df) <- "ave_steps"
int_df$interval <- as.integer(dimnames(int_df)[[1]])

imputed <- inner_join(data, int_df)
nas <- is.na(imputed$steps)
imputed$steps[nas] <- imputed$ave_steps[nas]

dayStepsIm <- with(imputed, tapply(steps, date, sum))
hist(dayStepsIm,
      breaks = 10,
     xlab = "Steps",
     main = "Daily Steps Taken, Using Imputed Values")
```

```{r, echo = TRUE}
mean(dayStepsIm)
median(dayStepsIm)
```

## Weekdays vs weekends.
```{r, echo = TRUE}
weekdays <- weekdays(imputed$date)
weekdays <- ifelse(weekdays %in% c("Saturday","Sunday"),
                   "Weekend",
                   "Weekday")
imputed$weekday <- as.factor(weekdays)

wkAvgs <- with(imputed, tapply(steps, list(interval, weekday), mean))
wkAvgs <- as.data.frame(wkAvgs)
wkAvgs$interval <- dimnames(wkAvgs)[[1]]
wkAvgs <- wkAvgs %>%
  melt(id = "interval", value.name = "steps")
names(wkAvgs)[2] <- "weekday"
wkAvgs$interval <- as.numeric(wkAvgs$interval)
```

```{r, echo = TRUE}
g <- ggplot(wkAvgs, aes(interval,steps))
g + geom_line() +
  facet_grid(. ~ weekday) +
  labs(x = "5-Minute Interval",
       y = "Steps",
       title = "Daily Average Step Count")
```

Weekend step activity seems somewhat higher with the glaring exception of weekday rush hour.


